{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 1) == 4", "trace": "def test_03():\n>       assert 2 +1 == 4\nE       assert (2 + 1) == 4\n\ntest_func01.py:13: AssertionError"}, "start": 1652499812054, "stop": 1652499812055, "uuid": "d274c0c4-d4aa-4ee0-93bb-4bafa8de6bb6", "historyId": "3178448805043da38f6850ec6bb6ea98", "testCaseId": "906e0004c232fccd35b7898e12ad6eb3", "fullName": "TestCase.test_func01#test_03", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_func01"}, {"name": "host", "value": "LAPTOP-RGTS8N0G"}, {"name": "thread", "value": "1904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_func01"}]}